from enum import Enum

from World.Object.Unit.Spell.Constants.Schools import Schools


class ObjectField(Enum):

    GUID                            = 0x0000  # Size: 2, Type: LONG, Flags: PUBLIC
    TYPE                            = 0x0002  # Size: 1, Type: INT, Flags: PUBLIC
    ENTRY                           = 0x0003  # Size: 1, Type: INT, Flags: PUBLIC
    SCALE_X                         = 0x0004  # Size: 1, Type: FLOAT, Flags: PUBLIC
    PADDING                         = 0x0005  # Size: 1, Type: INT, Flags: NONE
    END                             = 0x0006


class ItemField(Enum):

    OWNER                           = ObjectField.END.value + 0x0000  # Size: 2, Type: LONG, Flags: PUBLIC
    CONTAINED                       = ObjectField.END.value + 0x0002  # Size: 2, Type: LONG, Flags: PUBLIC
    CREATOR                         = ObjectField.END.value + 0x0004  # Size: 2, Type: LONG, Flags: PUBLIC
    GIFTCREATOR                     = ObjectField.END.value + 0x0006  # Size: 2, Type: LONG, Flags: PUBLIC
    STACK_COUNT                     = ObjectField.END.value + 0x0008  # Size: 1, Type: INT, Flags: OWNER_ONLY, UNK2
    DURATION                        = ObjectField.END.value + 0x0009  # Size: 1, Type: INT, Flags: OWNER_ONLY, UNK2
    SPELL_CHARGES                   = ObjectField.END.value + 0x000A  # Size: 5, Type: INT, Flags: OWNER_ONLY, UNK2
    FLAGS                           = ObjectField.END.value + 0x000F  # Size: 1, Type: INT, Flags: PUBLIC
    ENCHANTMENT                     = ObjectField.END.value + 0x0010  # Size: 33, Type: INT, Flags: PUBLIC
    PROPERTY_SEED                   = ObjectField.END.value + 0x0031  # Size: 1, Type: INT, Flags: PUBLIC
    RANDOM_PROPERTIES_ID            = ObjectField.END.value + 0x0032  # Size: 1, Type: INT, Flags: PUBLIC
    ITEM_TEXT_ID                    = ObjectField.END.value + 0x0033  # Size: 1, Type: INT, Flags: OWNER_ONLY
    DURABILITY                      = ObjectField.END.value + 0x0034  # Size: 1, Type: INT, Flags: OWNER_ONLY, UNK2
    MAXDURABILITY                   = ObjectField.END.value + 0x0035  # Size: 1, Type: INT, Flags: OWNER_ONLY, UNK2
    END                             = ObjectField.END.value + 0x0036


class ContainerField(Enum):

    NUM_SLOTS                       = ItemField.END.value + 0x0000 # Size: 1, Type: INT, Flags: PUBLIC
    ALIGN_PAD                       = ItemField.END.value + 0x0001 # Size: 1, Type: BYTES, Flags: NONE
    SLOT_1                          = ItemField.END.value + 0x0002 # Size: 72, Type: LONG, Flags: PUBLIC
    END                             = ItemField.END.value + 0x004A


class UnitField(Enum):

    CHARM                           = ObjectField.END.value + 0x0000 # Size: 2, Type: LONG, Flags: PUBLIC
    SUMMON                          = ObjectField.END.value + 0x0002 # Size: 2, Type: LONG, Flags: PUBLIC
    CHARMEDBY                       = ObjectField.END.value + 0x0004 # Size: 2, Type: LONG, Flags: PUBLIC
    SUMMONEDBY                      = ObjectField.END.value + 0x0006 # Size: 2, Type: LONG, Flags: PUBLIC
    CREATEDBY                       = ObjectField.END.value + 0x0008 # Size: 2, Type: LONG, Flags: PUBLIC
    TARGET                          = ObjectField.END.value + 0x000A # Size: 2, Type: LONG, Flags: PUBLIC
    PERSUADED                       = ObjectField.END.value + 0x000C # Size: 2, Type: LONG, Flags: PUBLIC
    CHANNEL_OBJECT                  = ObjectField.END.value + 0x000E # Size: 2, Type: LONG, Flags: PUBLIC
    HEALTH                          = ObjectField.END.value + 0x0010 # Size: 1, Type: INT, Flags: DYNAMIC
    POWER1                          = ObjectField.END.value + 0x0011 # Size: 1, Type: INT, Flags: PUBLIC
    POWER2                          = ObjectField.END.value + 0x0012 # Size: 1, Type: INT, Flags: PUBLIC
    POWER3                          = ObjectField.END.value + 0x0013 # Size: 1, Type: INT, Flags: PUBLIC
    POWER4                          = ObjectField.END.value + 0x0014 # Size: 1, Type: INT, Flags: PUBLIC
    POWER5                          = ObjectField.END.value + 0x0015 # Size: 1, Type: INT, Flags: PUBLIC
    MAXHEALTH                       = ObjectField.END.value + 0x0016 # Size: 1, Type: INT, Flags: DYNAMIC
    MAXPOWER1                       = ObjectField.END.value + 0x0017 # Size: 1, Type: INT, Flags: PUBLIC
    MAXPOWER2                       = ObjectField.END.value + 0x0018 # Size: 1, Type: INT, Flags: PUBLIC
    MAXPOWER3                       = ObjectField.END.value + 0x0019 # Size: 1, Type: INT, Flags: PUBLIC
    MAXPOWER4                       = ObjectField.END.value + 0x001A # Size: 1, Type: INT, Flags: PUBLIC
    MAXPOWER5                       = ObjectField.END.value + 0x001B # Size: 1, Type: INT, Flags: PUBLIC
    LEVEL                           = ObjectField.END.value + 0x001C # Size: 1, Type: INT, Flags: PUBLIC
    FACTIONTEMPLATE                 = ObjectField.END.value + 0x001D # Size: 1, Type: INT, Flags: PUBLIC
    BYTES_0                         = ObjectField.END.value + 0x001E # Size: 1, Type: BYTES, Flags: PUBLIC
    VIRTUAL_ITEM_SLOT_DISPLAY       = ObjectField.END.value + 0x001F # Size: 3, Type: INT, Flags: PUBLIC
    VIRTUAL_ITEM_INFO               = ObjectField.END.value + 0x0022 # Size: 6, Type: BYTES, Flags: PUBLIC
    FLAGS                           = ObjectField.END.value + 0x0028 # Size: 1, Type: INT, Flags: PUBLIC
    FLAGS_2                         = ObjectField.END.value + 0x0029 # Size: 1, Type: INT, Flags: PUBLIC
    AURA                            = ObjectField.END.value + 0x002A # Size: 56, Type: INT, Flags: PUBLIC
    AURAFLAGS                       = ObjectField.END.value + 0x0062 # Size: 14, Type: BYTES, Flags: PUBLIC
    AURALEVELS                      = ObjectField.END.value + 0x0070 # Size: 14, Type: BYTES, Flags: PUBLIC
    AURAAPPLICATIONS                = ObjectField.END.value + 0x007E # Size: 14, Type: BYTES, Flags: PUBLIC
    AURASTATE                       = ObjectField.END.value + 0x008C # Size: 1, Type: INT, Flags: PUBLIC
    BASEATTACKTIME                  = ObjectField.END.value + 0x008D # Size: 1, Type: INT, Flags: PUBLIC
    OFFHANDATTACKTIME               = ObjectField.END.value + 0x008E # Size: 1, Type: INT, Flags: PUBLIC
    RANGEDATTACKTIME                = ObjectField.END.value + 0x008F # Size: 1, Type: INT, Flags: PRIVATE
    BOUNDINGRADIUS                  = ObjectField.END.value + 0x0090 # Size: 1, Type: FLOAT, Flags: PUBLIC
    COMBATREACH                     = ObjectField.END.value + 0x0091 # Size: 1, Type: FLOAT, Flags: PUBLIC
    DISPLAYID                       = ObjectField.END.value + 0x0092 # Size: 1, Type: INT, Flags: PUBLIC
    NATIVEDISPLAYID                 = ObjectField.END.value + 0x0093 # Size: 1, Type: INT, Flags: PUBLIC
    MOUNTDISPLAYID                  = ObjectField.END.value + 0x0094 # Size: 1, Type: INT, Flags: PUBLIC
    MINDAMAGE                       = ObjectField.END.value + 0x0095 # Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY, UNK3
    MAXDAMAGE                       = ObjectField.END.value + 0x0096 # Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY, UNK3
    MINOFFHANDDAMAGE                = ObjectField.END.value + 0x0097 # Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY, UNK3
    MAXOFFHANDDAMAGE                = ObjectField.END.value + 0x0098 # Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY, UNK3
    BYTES_1                         = ObjectField.END.value + 0x0099 # Size: 1, Type: BYTES, Flags: PUBLIC
    PETNUMBER                       = ObjectField.END.value + 0x009A # Size: 1, Type: INT, Flags: PUBLIC
    PET_NAME_TIMESTAMP              = ObjectField.END.value + 0x009B # Size: 1, Type: INT, Flags: PUBLIC
    PETEXPERIENCE                   = ObjectField.END.value + 0x009C # Size: 1, Type: INT, Flags: OWNER_ONLY
    PETNEXTLEVELEXP                 = ObjectField.END.value + 0x009D # Size: 1, Type: INT, Flags: OWNER_ONLY
    DYNAMIC_FLAGS                   = ObjectField.END.value + 0x009E # Size: 1, Type: INT, Flags: DYNAMIC
    CHANNEL_SPELL                   = ObjectField.END.value + 0x009F # Size: 1, Type: INT, Flags: PUBLIC
    MOD_CAST_SPEED                  = ObjectField.END.value + 0x00A0 # Size: 1, Type: FLOAT, Flags: PUBLIC
    CREATED_BY_SPELL                = ObjectField.END.value + 0x00A1 # Size: 1, Type: INT, Flags: PUBLIC
    NPC_FLAGS                       = ObjectField.END.value + 0x00A2 # Size: 1, Type: INT, Flags: DYNAMIC
    NPC_EMOTESTATE                  = ObjectField.END.value + 0x00A3 # Size: 1, Type: INT, Flags: PUBLIC
    TRAINING_POINTS                 = ObjectField.END.value + 0x00A4 # Size: 1, Type: TWO_SHORT, Flags: OWNER_ONLY
    STAT0                           = ObjectField.END.value + 0x00A5 # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    STAT1                           = ObjectField.END.value + 0x00A6 # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    STAT2                           = ObjectField.END.value + 0x00A7 # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    STAT3                           = ObjectField.END.value + 0x00A8 # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    STAT4                           = ObjectField.END.value + 0x00A9 # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    POSSTAT0                        = ObjectField.END.value + 0x00AA # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    POSSTAT1                        = ObjectField.END.value + 0x00AB # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    POSSTAT2                        = ObjectField.END.value + 0x00AC # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    POSSTAT3                        = ObjectField.END.value + 0x00AD # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    POSSTAT4                        = ObjectField.END.value + 0x00AE # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    NEGSTAT0                        = ObjectField.END.value + 0x00AF # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    NEGSTAT1                        = ObjectField.END.value + 0x00B0 # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    NEGSTAT2                        = ObjectField.END.value + 0x00B1 # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    NEGSTAT3                        = ObjectField.END.value + 0x00B2 # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    NEGSTAT4                        = ObjectField.END.value + 0x00B3 # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY

    #RESISTANCES                     = ObjectField.END.value + 0x00B4 # Size: 7, Type: INT, Flags: PRIVATE, OWNER_ONLY, UNK3

    RESISTANCE_NORMAL               = ObjectField.END.value + 0x00B4 + Schools.SPELL_SCHOOL_NORMAL.value # armor
    RESISTANCE_HOLY                 = ObjectField.END.value + 0x00B4 + Schools.SPELL_SCHOOL_HOLY.value
    RESISTANCE_FIRE                 = ObjectField.END.value + 0x00B4 + Schools.SPELL_SCHOOL_FIRE.value
    RESISTANCE_NATURE               = ObjectField.END.value + 0x00B4 + Schools.SPELL_SCHOOL_NATURE.value
    RESISTANCE_FROST                = ObjectField.END.value + 0x00B4 + Schools.SPELL_SCHOOL_FROST.value
    RESISTANCE_SHADOW               = ObjectField.END.value + 0x00B4 + Schools.SPELL_SCHOOL_SHADOW.value
    RESISTANCE_ARCANE               = ObjectField.END.value + 0x00B4 + Schools.SPELL_SCHOOL_ARCANE.value

    RESISTANCE_NORMAL_BUFF_MOD_POS  = ObjectField.END.value + 0x00BB + Schools.SPELL_SCHOOL_NORMAL.value  # always 0 ?
    RESISTANCE_HOLY_BUFF_MOD_POS    = ObjectField.END.value + 0x00BB + Schools.SPELL_SCHOOL_HOLY.value    # always 0 ?
    RESISTANCE_FIRE_BUFF_MOD_POS    = ObjectField.END.value + 0x00BB + Schools.SPELL_SCHOOL_FIRE.value
    RESISTANCE_NATURE_BUFF_MOD_POS  = ObjectField.END.value + 0x00BB + Schools.SPELL_SCHOOL_NATURE.value
    RESISTANCE_FROST_BUFF_MOD_POS   = ObjectField.END.value + 0x00BB + Schools.SPELL_SCHOOL_FROST.value
    RESISTANCE_SHADOW_BUFF_MOD_POS  = ObjectField.END.value + 0x00BB + Schools.SPELL_SCHOOL_SHADOW.value
    RESISTANCE_ARCANE_BUFF_MOD_POS  = ObjectField.END.value + 0x00BB + Schools.SPELL_SCHOOL_ARCANE.value

    RESISTANCE_NORMAL_BUFF_MOD_NEG  = ObjectField.END.value + 0x00C2 + Schools.SPELL_SCHOOL_NORMAL.value  # always 0 ?
    RESISTANCE_HOLY_BUFF_MOD_NEG    = ObjectField.END.value + 0x00C2 + Schools.SPELL_SCHOOL_HOLY.value    # always 0 ?
    RESISTANCE_FIRE_BUFF_MOD_NEG    = ObjectField.END.value + 0x00C2 + Schools.SPELL_SCHOOL_FIRE.value
    RESISTANCE_NATURE_BUFF_MOD_NEG  = ObjectField.END.value + 0x00C2 + Schools.SPELL_SCHOOL_NATURE.value
    RESISTANCE_FROST_BUFF_MOD_NEG   = ObjectField.END.value + 0x00C2 + Schools.SPELL_SCHOOL_FROST.value
    RESISTANCE_SHADOW_BUFF_MOD_NEG  = ObjectField.END.value + 0x00C2 + Schools.SPELL_SCHOOL_SHADOW.value
    RESISTANCE_ARCANE_BUFF_MOD_NEG  = ObjectField.END.value + 0x00C2 + Schools.SPELL_SCHOOL_ARCANE.value

    BASE_MANA                       = ObjectField.END.value + 0x00C9 # Size: 1, Type: INT, Flags: PUBLIC
    BASE_HEALTH                     = ObjectField.END.value + 0x00CA # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    BYTES_2                         = ObjectField.END.value + 0x00CB # Size: 1, Type: BYTES, Flags: PUBLIC
    ATTACK_POWER                    = ObjectField.END.value + 0x00CC # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    ATTACK_POWER_MODS               = ObjectField.END.value + 0x00CD # Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER_ONLY
    ATTACK_POWER_MULTIPLIER         = ObjectField.END.value + 0x00CE # Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
    RANGED_ATTACK_POWER             = ObjectField.END.value + 0x00CF # Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    RANGED_ATTACK_POWER_MODS        = ObjectField.END.value + 0x00D0 # Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER_ONLY
    RANGED_ATTACK_POWER_MULTIPLIER  = ObjectField.END.value + 0x00D1 # Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
    MINRANGEDDAMAGE                 = ObjectField.END.value + 0x00D2 # Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
    MAXRANGEDDAMAGE                 = ObjectField.END.value + 0x00D3 # Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
    POWER_COST_MODIFIER             = ObjectField.END.value + 0x00D4 # Size: 7, Type: INT, Flags: PRIVATE, OWNER_ONLY
    POWER_COST_MULTIPLIER           = ObjectField.END.value + 0x00DB # Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
    MAXHEALTHMODIFIER               = ObjectField.END.value + 0x00E2 # Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
    PADDING                         = ObjectField.END.value + 0x00E3 # Size: 1, Type: INT, Flags: NONE
    END                             = ObjectField.END.value + 0x00E4


class PlayerField(Enum):
    DUEL_ARBITER                    = UnitField.END.value + 0x0000  # Size: 2, Type: LONG, Flags: PUBLIC
    FLAGS                           = UnitField.END.value + 0x0002  # Size: 1, Type: INT, Flags: PUBLIC
    GUILDID                         = UnitField.END.value + 0x0003  # Size: 1, Type: INT, Flags: PUBLIC
    GUILDRANK                       = UnitField.END.value + 0x0004  # Size: 1, Type: INT, Flags: PUBLIC
    BYTES_1                         = UnitField.END.value + 0x0005  # Size: 1, Type: BYTES, Flags: PUBLIC
    BYTES_2                         = UnitField.END.value + 0x0006  # Size: 1, Type: BYTES, Flags: PUBLIC
    BYTES_3                         = UnitField.END.value + 0x0007  # Size: 1, Type: BYTES, Flags: PUBLIC
    DUEL_TEAM                       = UnitField.END.value + 0x0008  # Size: 1, Type: INT, Flags: PUBLIC
    GUILD_TIMESTAMP                 = UnitField.END.value + 0x0009  # Size: 1, Type: INT, Flags: PUBLIC
    QUEST_LOG_1_1                   = UnitField.END.value + 0x000A  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_1_2                   = UnitField.END.value + 0x000B  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_1_3                   = UnitField.END.value + 0x000C  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_1_4                   = UnitField.END.value + 0x000D  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_2_1                   = UnitField.END.value + 0x000E  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_2_2                   = UnitField.END.value + 0x000F  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_2_3                   = UnitField.END.value + 0x0010  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_2_4                   = UnitField.END.value + 0x0011  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_3_1                   = UnitField.END.value + 0x0012  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_3_2                   = UnitField.END.value + 0x0013  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_3_3                   = UnitField.END.value + 0x0014  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_3_4                   = UnitField.END.value + 0x0015  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_4_1                   = UnitField.END.value + 0x0016  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_4_2                   = UnitField.END.value + 0x0017  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_4_3                   = UnitField.END.value + 0x0018  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_4_4                   = UnitField.END.value + 0x0019  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_5_1                   = UnitField.END.value + 0x001A  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_5_2                   = UnitField.END.value + 0x001B  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_5_3                   = UnitField.END.value + 0x001C  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_5_4                   = UnitField.END.value + 0x001D  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_6_1                   = UnitField.END.value + 0x001E  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_6_2                   = UnitField.END.value + 0x001F  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_6_3                   = UnitField.END.value + 0x0020  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_6_4                   = UnitField.END.value + 0x0021  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_7_1                   = UnitField.END.value + 0x0022  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_7_2                   = UnitField.END.value + 0x0023  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_7_3                   = UnitField.END.value + 0x0024  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_7_4                   = UnitField.END.value + 0x0025  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_8_1                   = UnitField.END.value + 0x0026  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_8_2                   = UnitField.END.value + 0x0027  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_8_3                   = UnitField.END.value + 0x0028  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_8_4                   = UnitField.END.value + 0x0029  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_9_1                   = UnitField.END.value + 0x002A  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_9_2                   = UnitField.END.value + 0x002B  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_9_3                   = UnitField.END.value + 0x002C  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_9_4                   = UnitField.END.value + 0x002D  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_10_1                  = UnitField.END.value + 0x002E  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_10_2                  = UnitField.END.value + 0x002F  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_10_3                  = UnitField.END.value + 0x0030  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_10_4                  = UnitField.END.value + 0x0031  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_11_1                  = UnitField.END.value + 0x0032  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_11_2                  = UnitField.END.value + 0x0033  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_11_3                  = UnitField.END.value + 0x0034  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_11_4                  = UnitField.END.value + 0x0035  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_12_1                  = UnitField.END.value + 0x0036  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_12_2                  = UnitField.END.value + 0x0037  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_12_3                  = UnitField.END.value + 0x0038  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_12_4                  = UnitField.END.value + 0x0039  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_13_1                  = UnitField.END.value + 0x003A  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_13_2                  = UnitField.END.value + 0x003B  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_13_3                  = UnitField.END.value + 0x003C  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_13_4                  = UnitField.END.value + 0x003D  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_14_1                  = UnitField.END.value + 0x003E  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_14_2                  = UnitField.END.value + 0x003F  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_14_3                  = UnitField.END.value + 0x0040  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_14_4                  = UnitField.END.value + 0x0041  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_15_1                  = UnitField.END.value + 0x0042  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_15_2                  = UnitField.END.value + 0x0043  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_15_3                  = UnitField.END.value + 0x0044  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_15_4                  = UnitField.END.value + 0x0045  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_16_1                  = UnitField.END.value + 0x0046  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_16_2                  = UnitField.END.value + 0x0047  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_16_3                  = UnitField.END.value + 0x0048  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_16_4                  = UnitField.END.value + 0x0049  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_17_1                  = UnitField.END.value + 0x004A  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_17_2                  = UnitField.END.value + 0x004B  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_17_3                  = UnitField.END.value + 0x004C  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_17_4                  = UnitField.END.value + 0x004D  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_18_1                  = UnitField.END.value + 0x004E  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_18_2                  = UnitField.END.value + 0x004F  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_18_3                  = UnitField.END.value + 0x0050  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_18_4                  = UnitField.END.value + 0x0051  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_19_1                  = UnitField.END.value + 0x0052  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_19_2                  = UnitField.END.value + 0x0053  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_19_3                  = UnitField.END.value + 0x0054  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_19_4                  = UnitField.END.value + 0x0055  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_20_1                  = UnitField.END.value + 0x0056  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_20_2                  = UnitField.END.value + 0x0057  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_20_3                  = UnitField.END.value + 0x0058  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_20_4                  = UnitField.END.value + 0x0059  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_21_1                  = UnitField.END.value + 0x005A  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_21_2                  = UnitField.END.value + 0x005B  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_21_3                  = UnitField.END.value + 0x005C  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_21_4                  = UnitField.END.value + 0x005D  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_22_1                  = UnitField.END.value + 0x005E  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_22_2                  = UnitField.END.value + 0x005F  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_22_3                  = UnitField.END.value + 0x0060  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_22_4                  = UnitField.END.value + 0x0061  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_23_1                  = UnitField.END.value + 0x0062  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_23_2                  = UnitField.END.value + 0x0063  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_23_3                  = UnitField.END.value + 0x0064  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_23_4                  = UnitField.END.value + 0x0065  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_24_1                  = UnitField.END.value + 0x0066  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_24_2                  = UnitField.END.value + 0x0067  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_24_3                  = UnitField.END.value + 0x0068  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_24_4                  = UnitField.END.value + 0x0069  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_25_1                  = UnitField.END.value + 0x006A  # Size: 1, Type: INT, Flags: GROUP_ONLY
    QUEST_LOG_25_2                  = UnitField.END.value + 0x006B  # Size: 1, Type: INT, Flags: PRIVATE
    QUEST_LOG_25_3                  = UnitField.END.value + 0x006C  # Size: 1, Type: BYTES, Flags: PRIVATE
    QUEST_LOG_25_4                  = UnitField.END.value + 0x006D  # Size: 1, Type: INT, Flags: PRIVATE
    VISIBLE_ITEM_1_CREATOR          = UnitField.END.value + 0x006E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_1_0                = UnitField.END.value + 0x0070  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_1_PROPERTIES       = UnitField.END.value + 0x007C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_1_PAD              = UnitField.END.value + 0x007D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_2_CREATOR          = UnitField.END.value + 0x007E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_2_0                = UnitField.END.value + 0x0080  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_2_PROPERTIES       = UnitField.END.value + 0x008C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_2_PAD              = UnitField.END.value + 0x008D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_3_CREATOR          = UnitField.END.value + 0x008E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_3_0                = UnitField.END.value + 0x0090  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_3_PROPERTIES       = UnitField.END.value + 0x009C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_3_PAD              = UnitField.END.value + 0x009D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_4_CREATOR          = UnitField.END.value + 0x009E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_4_0                = UnitField.END.value + 0x00A0  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_4_PROPERTIES       = UnitField.END.value + 0x00AC  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_4_PAD              = UnitField.END.value + 0x00AD  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_5_CREATOR          = UnitField.END.value + 0x00AE  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_5_0                = UnitField.END.value + 0x00B0  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_5_PROPERTIES       = UnitField.END.value + 0x00BC  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_5_PAD              = UnitField.END.value + 0x00BD  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_6_CREATOR          = UnitField.END.value + 0x00BE  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_6_0                = UnitField.END.value + 0x00C0  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_6_PROPERTIES       = UnitField.END.value + 0x00CC  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_6_PAD              = UnitField.END.value + 0x00CD  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_7_CREATOR          = UnitField.END.value + 0x00CE  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_7_0                = UnitField.END.value + 0x00D0  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_7_PROPERTIES       = UnitField.END.value + 0x00DC  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_7_PAD              = UnitField.END.value + 0x00DD  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_8_CREATOR          = UnitField.END.value + 0x00DE  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_8_0                = UnitField.END.value + 0x00E0  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_8_PROPERTIES       = UnitField.END.value + 0x00EC  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_8_PAD              = UnitField.END.value + 0x00ED  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_9_CREATOR          = UnitField.END.value + 0x00EE  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_9_0                = UnitField.END.value + 0x00F0  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_9_PROPERTIES       = UnitField.END.value + 0x00FC  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_9_PAD              = UnitField.END.value + 0x00FD  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_10_CREATOR         = UnitField.END.value + 0x00FE  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_10_0               = UnitField.END.value + 0x0100  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_10_PROPERTIES      = UnitField.END.value + 0x010C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_10_PAD             = UnitField.END.value + 0x010D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_11_CREATOR         = UnitField.END.value + 0x010E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_11_0               = UnitField.END.value + 0x0110  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_11_PROPERTIES      = UnitField.END.value + 0x011C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_11_PAD             = UnitField.END.value + 0x011D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_12_CREATOR         = UnitField.END.value + 0x011E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_12_0               = UnitField.END.value + 0x0120  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_12_PROPERTIES      = UnitField.END.value + 0x012C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_12_PAD             = UnitField.END.value + 0x012D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_13_CREATOR         = UnitField.END.value + 0x012E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_13_0               = UnitField.END.value + 0x0130  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_13_PROPERTIES      = UnitField.END.value + 0x013C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_13_PAD             = UnitField.END.value + 0x013D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_14_CREATOR         = UnitField.END.value + 0x013E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_14_0               = UnitField.END.value + 0x0140  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_14_PROPERTIES      = UnitField.END.value + 0x014C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_14_PAD             = UnitField.END.value + 0x014D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_15_CREATOR         = UnitField.END.value + 0x014E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_15_0               = UnitField.END.value + 0x0150  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_15_PROPERTIES      = UnitField.END.value + 0x015C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_15_PAD             = UnitField.END.value + 0x015D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_16_CREATOR         = UnitField.END.value + 0x015E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_16_0               = UnitField.END.value + 0x0160  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_16_PROPERTIES      = UnitField.END.value + 0x016C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_16_PAD             = UnitField.END.value + 0x016D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_17_CREATOR         = UnitField.END.value + 0x016E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_17_0               = UnitField.END.value + 0x0170  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_17_PROPERTIES      = UnitField.END.value + 0x017C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_17_PAD             = UnitField.END.value + 0x017D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_18_CREATOR         = UnitField.END.value + 0x017E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_18_0               = UnitField.END.value + 0x0180  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_18_PROPERTIES      = UnitField.END.value + 0x018C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_18_PAD             = UnitField.END.value + 0x018D  # Size: 1, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_19_CREATOR         = UnitField.END.value + 0x018E  # Size: 2, Type: LONG, Flags: PUBLIC
    VISIBLE_ITEM_19_0               = UnitField.END.value + 0x0190  # Size: 12, Type: INT, Flags: PUBLIC
    VISIBLE_ITEM_19_PROPERTIES      = UnitField.END.value + 0x019C  # Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    VISIBLE_ITEM_19_PAD             = UnitField.END.value + 0x019D  # Size: 1, Type: INT, Flags: PUBLIC

    CHOSEN_TITLE                    = UnitField.END.value + 0x019E  # Size: 1, Type: INT, Flags: PUBLIC
    PAD_0                           = UnitField.END.value + 0x019F  # Size: 1, Type: INT, Flags: NONE
    INV_SLOT_HEAD                   = UnitField.END.value + 0x01A0  # Size: 46, Type: LONG, Flags: PRIVATE
    INV_SLOT_NECK                   = INV_SLOT_HEAD + 2
    INV_SLOT_SHOULDERS              = INV_SLOT_HEAD + 4
    INV_SLOT_BODY                   = INV_SLOT_HEAD + 6
    INV_SLOT_CHEST                  = INV_SLOT_HEAD + 8
    INV_SLOT_WAIST                  = INV_SLOT_HEAD + 10
    INV_SLOT_LEGS                   = INV_SLOT_HEAD + 12
    INV_SLOT_FEET                   = INV_SLOT_HEAD + 14
    INV_SLOT_WRISTS                 = INV_SLOT_HEAD + 16
    INV_SLOT_HANDS                  = INV_SLOT_HEAD + 18
    INV_SLOT_FINGER1                = INV_SLOT_HEAD + 20
    INV_SLOT_FINGER2                = INV_SLOT_HEAD + 22
    INV_SLOT_TRINKET1               = INV_SLOT_HEAD + 24
    INV_SLOT_TRINKET2               = INV_SLOT_HEAD + 26
    INV_SLOT_BACK                   = INV_SLOT_HEAD + 28
    INV_SLOT_MAINHAND               = INV_SLOT_HEAD + 30
    INV_SLOT_OFFHAND                = INV_SLOT_HEAD + 32
    INV_SLOT_RANGED                 = INV_SLOT_HEAD + 34
    INV_SLOT_TABARD                 = INV_SLOT_HEAD + 36
    INV_SLOT_BAG1                   = INV_SLOT_HEAD + 38
    INV_SLOT_BAG2                   = INV_SLOT_HEAD + 40
    INV_SLOT_BAG3                   = INV_SLOT_HEAD + 42
    INV_SLOT_BAG4                   = INV_SLOT_HEAD + 44

    PACK_SLOT_1                     = UnitField.END.value + 0x01CE  # Size: 32, Type: LONG, Flags: PRIVATE
    BANK_SLOT_1                     = UnitField.END.value + 0x01EE  # Size: 56, Type: LONG, Flags: PRIVATE
    BANKBAG_SLOT_1                  = UnitField.END.value + 0x0226  # Size: 14, Type: LONG, Flags: PRIVATE
    VENDORBUYBACK_SLOT_1            = UnitField.END.value + 0x0234  # Size: 24, Type: LONG, Flags: PRIVATE
    KEYRING_SLOT_1                  = UnitField.END.value + 0x024C  # Size: 64, Type: LONG, Flags: PRIVATE
    VANITYPET_SLOT_1                = UnitField.END.value + 0x028C  # Size: 36, Type: LONG, Flags: PRIVATE
    FARSIGHT                        = UnitField.END.value + 0x02B0  # Size: 2, Type: LONG, Flags: PRIVATE
    _FIELD_KNOWN_TITLES             = UnitField.END.value + 0x02B2  # Size: 2, Type: LONG, Flags: PRIVATE
    XP                              = UnitField.END.value + 0x02B4  # Size: 1, Type: INT, Flags: PRIVATE
    NEXT_LEVEL_XP                   = UnitField.END.value + 0x02B5  # Size: 1, Type: INT, Flags: PRIVATE
    SKILL_INFO_1_ID                 = UnitField.END.value + 0x02B6  # Size: 384, Type: TWO_SHORT, Flags: PRIVATE
    SKILL_INFO_1_LEVEL              = UnitField.END.value + 0x02B7
    SKILL_INFO_1_STAT_LEVEL         = UnitField.END.value + 0x02B8

    CHARACTER_POINTS1               = UnitField.END.value + 0x0436  # Size: 1, Type: INT, Flags: PRIVATE
    CHARACTER_POINTS2               = UnitField.END.value + 0x0437  # Size: 1, Type: INT, Flags: PRIVATE
    TRACK_CREATURES                 = UnitField.END.value + 0x0438  # Size: 1, Type: INT, Flags: PRIVATE
    TRACK_RESOURCES                 = UnitField.END.value + 0x0439  # Size: 1, Type: INT, Flags: PRIVATE
    BLOCK_PERCENTAGE                = UnitField.END.value + 0x043A  # Size: 1, Type: FLOAT, Flags: PRIVATE
    DODGE_PERCENTAGE                = UnitField.END.value + 0x043B  # Size: 1, Type: FLOAT, Flags: PRIVATE
    PARRY_PERCENTAGE                = UnitField.END.value + 0x043C  # Size: 1, Type: FLOAT, Flags: PRIVATE
    EXPERTISE                       = UnitField.END.value + 0x043D  # Size: 1, Type: INT, Flags: PRIVATE
    OFFHAND_EXPERTISE               = UnitField.END.value + 0x043E  # Size: 1, Type: INT, Flags: PRIVATE
    CRIT_PERCENTAGE                 = UnitField.END.value + 0x043F  # Size: 1, Type: FLOAT, Flags: PRIVATE
    RANGED_CRIT_PERCENTAGE          = UnitField.END.value + 0x0440  # Size: 1, Type: FLOAT, Flags: PRIVATE
    OFFHAND_CRIT_PERCENTAGE         = UnitField.END.value + 0x0441  # Size: 1, Type: FLOAT, Flags: PRIVATE

    #SPELL_CRIT_PERCENTAGE1          = UnitField.END.value + 0x0442  # Size: 7, Type: FLOAT, Flags: PRIVATE
    SPELL_CRIT_NORMAL_PERCENTAGE    = UnitField.END.value + 0x0442 + Schools.SPELL_SCHOOL_NORMAL.value  # always 0 ?
    SPELL_CRIT_HOLY_PERCENTAGE      = UnitField.END.value + 0x0442 + Schools.SPELL_SCHOOL_HOLY.value
    SPELL_CRIT_FIRE_PERCENTAGE      = UnitField.END.value + 0x0442 + Schools.SPELL_SCHOOL_FIRE.value
    SPELL_CRIT_NATURE_PERCENTAGE    = UnitField.END.value + 0x0442 + Schools.SPELL_SCHOOL_NATURE.value
    SPELL_CRIT_FROST_PERCENTAGE     = UnitField.END.value + 0x0442 + Schools.SPELL_SCHOOL_FROST.value
    SPELL_CRIT_SHADOW_PERCENTAGE    = UnitField.END.value + 0x0442 + Schools.SPELL_SCHOOL_SHADOW.value
    SPELL_CRIT_ARCANE_PERCENTAGE    = UnitField.END.value + 0x0442 + Schools.SPELL_SCHOOL_ARCANE.value

    SHIELD_BLOCK                    = UnitField.END.value + 0x0449  # Size: 1, Type: INT, Flags: PRIVATE
    EXPLORED_ZONES_1                = UnitField.END.value + 0x044A  # Size: 128, Type: BYTES, Flags: PRIVATE
    REST_STATE_EXPERIENCE           = UnitField.END.value + 0x04CA  # Size: 1, Type: INT, Flags: PRIVATE
    COINAGE                         = UnitField.END.value + 0x04CB  # Size: 1, Type: INT, Flags: PRIVATE

    MOD_DAMAGE_DONE_POS             = UnitField.END.value + 0x04CC  # Size: 7, Type: INT, Flags: PRIVATE
    # MOD_DAMAGE_NORMAL_DONE_POS      = UnitField.END.value + 0x04CC + Schools.SPELL_SCHOOL_NORMAL.value
    # MOD_DAMAGE_HOLY_DONE_POS        = UnitField.END.value + 0x04CC + Schools.SPELL_SCHOOL_HOLY.value
    # MOD_DAMAGE_FIRE_DONE_POS        = UnitField.END.value + 0x04CC + Schools.SPELL_SCHOOL_FIRE.value
    # MOD_DAMAGE_NATURE_DONE_POS      = UnitField.END.value + 0x04CC + Schools.SPELL_SCHOOL_NATURE.value
    # MOD_DAMAGE_FROST_DONE_POS       = UnitField.END.value + 0x04CC + Schools.SPELL_SCHOOL_FROST.value
    # MOD_DAMAGE_SHADOW_DONE_POS      = UnitField.END.value + 0x04CC + Schools.SPELL_SCHOOL_SHADOW.value
    # MOD_DAMAGE_ARCANE_DONE_POS      = UnitField.END.value + 0x04CC + Schools.SPELL_SCHOOL_ARCANE.value

    MOD_DAMAGE_DONE_NEG             = UnitField.END.value + 0x04D3  # Size: 7, Type: INT, Flags: PRIVATE
    # MOD_DAMAGE_NORMAL_DONE_NEG      = UnitField.END.value + 0x04D3 + Schools.SPELL_SCHOOL_NORMAL.value
    # MOD_DAMAGE_HOLY_DONE_NEG        = UnitField.END.value + 0x04D3 + Schools.SPELL_SCHOOL_HOLY.value
    # MOD_DAMAGE_FIRE_DONE_NEG        = UnitField.END.value + 0x04D3 + Schools.SPELL_SCHOOL_FIRE.value
    # MOD_DAMAGE_NATURE_DONE_NEG      = UnitField.END.value + 0x04D3 + Schools.SPELL_SCHOOL_NATURE.value
    # MOD_DAMAGE_FROST_DONE_NEG       = UnitField.END.value + 0x04D3 + Schools.SPELL_SCHOOL_FROST.value
    # MOD_DAMAGE_SHADOW_DONE_NEG      = UnitField.END.value + 0x04D3 + Schools.SPELL_SCHOOL_SHADOW.value
    # MOD_DAMAGE_ARCANE_DONE_NEG      = UnitField.END.value + 0x04D3 + Schools.SPELL_SCHOOL_ARCANE.value

    MOD_DAMAGE_DONE_PCT             = UnitField.END.value + 0x04DA  # Size: 7, Type: INT, Flags: PRIVATE
    MOD_DAMAGE_NORMAL_DONE_PCT      = UnitField.END.value + 0x04DA + Schools.SPELL_SCHOOL_NORMAL.value
    MOD_DAMAGE_HOLY_DONE_PCT        = UnitField.END.value + 0x04DA + Schools.SPELL_SCHOOL_HOLY.value
    MOD_DAMAGE_FIRE_DONE_PCT        = UnitField.END.value + 0x04DA + Schools.SPELL_SCHOOL_FIRE.value
    MOD_DAMAGE_NATURE_DONE_PCT      = UnitField.END.value + 0x04DA + Schools.SPELL_SCHOOL_NATURE.value
    MOD_DAMAGE_FROST_DONE_PCT       = UnitField.END.value + 0x04DA + Schools.SPELL_SCHOOL_FROST.value
    MOD_DAMAGE_SHADOW_DONE_PCT      = UnitField.END.value + 0x04DA + Schools.SPELL_SCHOOL_SHADOW.value
    MOD_DAMAGE_ARCANE_DONE_PCT      = UnitField.END.value + 0x04DA + Schools.SPELL_SCHOOL_ARCANE.value

    MOD_HEALING_DONE_POS            = UnitField.END.value + 0x04E1  # Size: 1, Type: INT, Flags: PRIVATE
    MOD_TARGET_RESISTANCE           = UnitField.END.value + 0x04E2  # Size: 1, Type: INT, Flags: PRIVATE
    MOD_TARGET_PHYSICAL_RESISTANCE  = UnitField.END.value + 0x04E3  # Size: 1, Type: INT, Flags: PRIVATE
    BYTES                           = UnitField.END.value + 0x04E4  # Size: 1, Type: BYTES, Flags: PRIVATE
    AMMO_ID                         = UnitField.END.value + 0x04E5  # Size: 1, Type: INT, Flags: PRIVATE
    SELF_RES_SPELL                  = UnitField.END.value + 0x04E6  # Size: 1, Type: INT, Flags: PRIVATE
    PVP_MEDALS                      = UnitField.END.value + 0x04E7  # Size: 1, Type: INT, Flags: PRIVATE
    BUYBACK_PRICE_1                 = UnitField.END.value + 0x04E8  # Size: 12, Type: INT, Flags: PRIVATE
    BUYBACK_TIMESTAMP_1             = UnitField.END.value + 0x04F4  # Size: 12, Type: INT, Flags: PRIVATE
    KILLS                           = UnitField.END.value + 0x0500  # Size: 1, Type: TWO_SHORT, Flags: PRIVATE
    TODAY_CONTRIBUTION              = UnitField.END.value + 0x0501  # Size: 1, Type: INT, Flags: PRIVATE
    YESTERDAY_CONTRIBUTION          = UnitField.END.value + 0x0502  # Size: 1, Type: INT, Flags: PRIVATE
    LIFETIME_HONORABLE_KILLS        = UnitField.END.value + 0x0503  # Size: 1, Type: INT, Flags: PRIVATE
    BYTES2                          = UnitField.END.value + 0x0504  # Size: 1, Type: BYTES, Flags: PRIVATE
    WATCHED_FACTION_INDEX           = UnitField.END.value + 0x0505  # Size: 1, Type: INT, Flags: PRIVATE
    COMBAT_RATING_1                 = UnitField.END.value + 0x0506  # Size: 24, Type: INT, Flags: PRIVATE
    ARENA_TEAM_INFO_1_1             = UnitField.END.value + 0x051E  # Size: 18, Type: INT, Flags: PRIVATE
    HONOR_CURRENCY                  = UnitField.END.value + 0x0530  # Size: 1, Type: INT, Flags: PRIVATE
    ARENA_CURRENCY                  = UnitField.END.value + 0x0531  # Size: 1, Type: INT, Flags: PRIVATE
    MOD_MANA_REGEN                  = UnitField.END.value + 0x0532  # Size: 1, Type: FLOAT, Flags: PRIVATE
    MOD_MANA_REGEN_INTERRUPT        = UnitField.END.value + 0x0533  # Size: 1, Type: FLOAT, Flags: PRIVATE
    MAX_LEVEL                       = UnitField.END.value + 0x0534  # Size: 1, Type: INT, Flags: PRIVATE
    DAILY_QUESTS_1                  = UnitField.END.value + 0x0535  # Size: 25, Type: INT, Flags: PRIVATE
    END                             = UnitField.END.value + 0x054E
