from World.Object.Constants.UpdateObjectFields import ObjectField, UnitField, PlayerField


PLAYER_SPAWN_FIELDS = [
    # Object fields
    ObjectField.GUID,
    ObjectField.TYPE,
    ObjectField.SCALE_X,

    # Unit fields
    UnitField.HEALTH,
    UnitField.MAXHEALTH,
    UnitField.LEVEL,
    UnitField.FACTIONTEMPLATE,
    UnitField.BYTES_0,
    UnitField.FLAGS,
    UnitField.BOUNDINGRADIUS,
    UnitField.COMBATREACH,
    UnitField.DISPLAYID,
    UnitField.NATIVEDISPLAYID,
    UnitField.STAT0,
    UnitField.STAT1,
    UnitField.STAT2,
    UnitField.STAT3,
    UnitField.STAT4,
    UnitField.RESISTANCE_NORMAL,
    UnitField.BASE_HEALTH,

    # Player fields
    PlayerField.FLAGS,
    PlayerField.BYTES_1,
    PlayerField.BYTES_2,

    PlayerField.VISIBLE_ITEM_1_0,
    PlayerField.VISIBLE_ITEM_2_0,
    PlayerField.VISIBLE_ITEM_3_0,
    PlayerField.VISIBLE_ITEM_4_0,
    PlayerField.VISIBLE_ITEM_5_0,
    PlayerField.VISIBLE_ITEM_6_0,
    PlayerField.VISIBLE_ITEM_7_0,
    PlayerField.VISIBLE_ITEM_8_0,
    PlayerField.VISIBLE_ITEM_9_0,
    PlayerField.VISIBLE_ITEM_10_0,
    PlayerField.VISIBLE_ITEM_11_0,
    PlayerField.VISIBLE_ITEM_12_0,
    PlayerField.VISIBLE_ITEM_13_0,
    PlayerField.VISIBLE_ITEM_14_0,
    PlayerField.VISIBLE_ITEM_15_0,
    PlayerField.VISIBLE_ITEM_16_0,
    PlayerField.VISIBLE_ITEM_17_0,

    PlayerField.INV_SLOT_HEAD,
    PlayerField.INV_SLOT_NECK,
    PlayerField.INV_SLOT_SHOULDERS,
    PlayerField.INV_SLOT_BODY,
    PlayerField.INV_SLOT_CHEST,
    PlayerField.INV_SLOT_WAIST,
    PlayerField.INV_SLOT_LEGS,
    PlayerField.INV_SLOT_FEET,
    PlayerField.INV_SLOT_WRISTS,
    PlayerField.INV_SLOT_HANDS,
    PlayerField.INV_SLOT_FINGER1,
    PlayerField.INV_SLOT_FINGER2,
    PlayerField.INV_SLOT_TRINKET1,
    PlayerField.INV_SLOT_TRINKET2,
    PlayerField.INV_SLOT_BACK,
    PlayerField.INV_SLOT_MAINHAND,
    PlayerField.INV_SLOT_OFFHAND,
    PlayerField.INV_SLOT_RANGED,
    PlayerField.INV_SLOT_TABARD,

    PlayerField.XP,
    PlayerField.NEXT_LEVEL_XP,
    PlayerField.CHARACTER_POINTS1,
    PlayerField.CHARACTER_POINTS2,
    PlayerField.SHIELD_BLOCK,
    PlayerField.EXPLORED_ZONES_1,
    PlayerField.MOD_DAMAGE_NORMAL_DONE_PCT,
    PlayerField.BYTES,
    PlayerField.WATCHED_FACTION_INDEX,
    PlayerField.MAX_LEVEL,
    PlayerField.COINAGE
]
