# Object Events
CHANGE_POSITION = 1
SPAWN = 2
DESPAWN = 3

# Region Events
WEATHER_SET_FINE = 4
WEATHER_SET_RAIN = 5
WEATHER_SET_SNOW = 6
WEATHER_SET_STORM = 7
WEATHER_SET_THUNDERS = 8
WEATHER_SET_BLACK_RAIN = 9
